[package]
name = "core_data_client"
version = "0.2.0"
authors = ["Augustus Mayo <gusmayo@gmail.com>"]

[dependencies]
hyper = "0.9.12"

[dev-dependencies]
assert_matches = "1.0"
mockito = "0.2.2"
uuid = { version = "0.2", features = ["v4"] }
