[package]
authors = ["Augustus Mayo <gusmayo@gmail.com>"]
name = "mm_client"
version = "0.7.0"

[dependencies]
reqwest = "0.3.0"

[dev-dependencies]
assert_matches = "1.0"
mockito = "0.2.2"

[dev-dependencies.uuid]
features = ["v4"]
version = "0.2"
