[package]
authors = ["Augustus Mayo <gusmayo@gmail.com>"]
name = "mm_client"
version = "0.8.1"

[dependencies]
reqwest = "0.4.0"
serde = "0.9.7"
serde_json = "0.9.6"

[dev-dependencies]
assert_matches = "1.0"
mockito = "0.2.2"

[dev-dependencies.uuid]
features = ["v4"]
version = "0.2"
