version: 2
jobs:
  checkout:
    docker:
      - image: scorpil/rust:stable
    steps:
      - restore_cache:
          key: repo-{{ .Branch }}
      - checkout
      - run: echo $CIRCLE_SHA1 > .circle-sha
      - save_cache:
          key: repo-{{ .Branch }}-{{ checksum ".circle-sha" }}
          paths:
            - ~/project
    test:
      docker:
        - image: scorpil/rust:stable
      steps:
        - restore_cache:
            key: repo-{{ .Branch }}
      run: cargo test

    build:
      docker:
        - image: scorpil/rust:stable
      steps:
        - restore_cache:
            key: repo-{{ .Branch }}
      run: cargo build --release

workflows:
  version: 2
  test_and_build:
    jobs:
      - checkout
      - test:
          requires:
            - checkout
      - build:
          requires:
            - checkout