version: 2
jobs:
  test:
    docker:
      - image: scorpil/rust:stable
    steps:
      - checkout
      - run: cargo test

  build:
    docker:
      - image: scorpil/rust:stable
    steps:
      - checkout
      - run: cargo build --release

workflows:
  version: 2
  test_and_build:
    jobs:
      - test
      - build