version: 2
jobs:
  test:
    docker:
      - image: clux/muslrust
        auth:
          username: $DOCKERHUB_ACCOUNT 
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - run: cargo test

  build:
    docker:
      - image: clux/muslrust
        auth:
          username: $DOCKERHUB_ACCOUNT 
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - run: cargo build --release --features cli

workflows:
  version: 2
  test_and_build:
    jobs:
      - test
      - build